version: "3.8"

services:
  solr:
    image: solr:latest
    container_name: restaurant-service-solr
    ports:
      - "8983:8983"
    volumes:
      - ./data:/var/solr
    command:
      - solr-precreate
      - restaurants
    networks:
      - spring-cloud-network

  restaurant-service:
    container_name: restaurant-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - solr
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    external: true
