version: "3.8"

services:
  user-service:
    container_name: user-service
    build:
      context: user-service
      dockerfile: ./Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - userdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://userdb:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_HIBERNATE_SHOW-SQL=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  userdb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=userdb

  logger:
    container_name: logger
    build:
      context: logger
      dockerfile: ./Dockerfile
    image: logger:latest
    ports:
      - "8082:8082"
    depends_on:
      - loggerdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://loggerdb:5432/loggerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_HIBERNATE_SHOW-SQL=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  loggerdb:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=loggerdb

  solr:
    image: solr:latest
    container_name: restaurant-service-solr
    ports:
      - "8983:8983"
    volumes:
      - ./restaurant-service/data:/var/solr
    command:
      - solr-precreate
      - restaurants

  restaurant-service:
    container_name: restaurant-service
    build:
      context: restaurant-service
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - solr
    environment:
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
